export const countries = [
	{ country: "Украина", price: 100 },
	{ country: "Черногория", price: 120 },
	{ country: "Венгрия", price: 150 },
	{ country: "Словакия", price: 150 },
	{ country: "Польща", price: 150 },
	{ country: "Чехия", price: 150 },
	{ country: "Хорватия", price: 150 },
	{ country: "Литва", price: 150 },
	{ country: "Словения", price: 150 },
	{ country: "Латвия", price: 150 },
	{ country: "Австрия", price: 200 },
	{ country: "Греция", price: 200 },
	{ country: "Турция", price: 200 },
	{ country: "Италия", price: 200 },
	{ country: "Франция", price: 200 },
	{ country: "Германия", price: 200 },
	{ country: "Нидерланды", price: 200 },
	{ country: "Бельгия", price: 200 },
	{ country: "Испания", price: 200 },
	{ country: "Португалия", price: 200 },
	{ country: "Мальта", price: 200 },
	{ country: "Швеция", price: 250 },
	{ country: "Исландия", price: 250 },
	{ country: "Норвегия", price: 250 },
	{ country: "Финляндия", price: 250 },
	{ country: "Дания", price: 250 },
]